apiVersion: v1
kind: configMap
metadata: 
  name: pod-config
data:
  course: "DevSecOps with AWS"
  trainer: Siva



# kubectl apply -f 06-config-map.yaml
# kubectl get configmap
# kubectl describe configmap pod-config

# how to refer in pod ?


