apiVersion: v1
kind: Pod
metadata: 
   name: resources-demo
spec: 
   containers:
   - name: nginx 
     image: nginx
     resources: 
        requests: 
           memory: "68Mi"
           cpu: "100m"
      # provide equal or more than request
        limits:
            memory: "100Mi"
            cpu: "120m"